name: CICD

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t ganidu2413/mmsystem-frontend .
      - name: Publish image to docker hub
        run: docker push ganidu2413/mmsystem-frontend:latest

  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      - name: Pull image from docker hub
        rub: docker pull ganidu2413/mmsystem-frontend:latest
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: docker run -d -p 3000:80 --name reactContainer ganidu2413/mmsystem-frontend

